import express from 'express'; import crypto from 'node:crypto';
import {Connection,Keypair,PublicKey,SystemProgram,Transaction,sendAndConfirmTransaction,LAMPORTS_PER_SOL} from '@solana/web3.js';
import bs58 from 'bs58';
const app=express();app.use(express.json());app.use(express.static('public'));const rounds=[];let settings={tokenMint:process.env.TOKEN_MINT||'',feeWallet:process.env.FEE_WALLET||'',rewardBps:5000,intervalMinutes:5,status:process.env.TOKEN_MINT&&process.env.FEE_WALLET?'ready':'setup'},watermark=null,busy=false;
const rpc=new Connection(process.env.SOLANA_RPC_URL||'https://api.mainnet-beta.solana.com','confirmed');
const auth=(q,s,n)=>q.header('x-admin-token')===process.env.ADMIN_TOKEN?n():s.status(401).json({error:'Unauthorized'});const signer=()=>process.env.TREASURY_PRIVATE_KEY?Keypair.fromSecretKey(bs58.decode(process.env.TREASURY_PRIVATE_KEY)):Keypair.fromSecretKey(Uint8Array.from(JSON.parse(process.env.TREASURY_KEYPAIR_JSON||'[]')));
async function holders(){const mint=new PublicKey(settings.tokenMint),r=await rpc.getParsedProgramAccounts(new PublicKey('TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'),{filters:[{dataSize:165},{memcmp:{offset:0,bytes:mint.toBase58()}}]}),m=new Map();for(const x of r){const a=x.account.data.parsed.info;if(a.tokenAmount.uiAmount>0&&a.owner!==settings.feeWallet)m.set(a.owner,(m.get(a.owner)||0)+a.tokenAmount.uiAmount)}const t=[...m.values()].reduce((a,b)=>a+b,0);return [...m].map(([wallet,balance])=>({wallet,weight:balance/t*100}))}
async function distribute(fees){const h=await holders(),reward=Math.floor(fees*.5),kp=signer(),p=h.map(x=>({wallet:x.wallet,lamports:Math.floor(reward*x.weight/100)})).filter(x=>x.lamports>5000);if(!p.length)throw Error('No eligible holders');for(let i=0;i<p.length;i+=16){const tx=new Transaction();p.slice(i,i+16).forEach(x=>tx.add(SystemProgram.transfer({fromPubkey:kp.publicKey,toPubkey:new PublicKey(x.wallet),lamports:x.lamports})));await sendAndConfirmTransaction(rpc,tx,[kp])}rounds.push({id:crypto.randomUUID(),createdAt:new Date().toISOString(),feeAmount:fees/LAMPORTS_PER_SOL,rewardPool:reward/LAMPORTS_PER_SOL,keptByCreator:(fees-reward)/LAMPORTS_PER_SOL,status:'paid',holders:p.length})}
async function cycle(){if(busy||settings.status!=='ready'||process.env.AUTO_DISTRIBUTE!=='true')return;busy=true;try{const b=await rpc.getBalance(new PublicKey(settings.feeWallet));if(watermark===null)watermark=b;else if(b-watermark>10000){await distribute(b-watermark);watermark=await rpc.getBalance(new PublicKey(settings.feeWallet))}}catch(e){console.error('cycle',e.message)}finally{busy=false}}
app.get('/api/health',(q,s)=>s.json({ok:true,mode:settings.status,rounds:rounds.length,autoDistribution:process.env.AUTO_DISTRIBUTE==='true'}));app.get('/api/dashboard',(q,s)=>s.json({settings,rounds:rounds.slice(-8).reverse(),totalDistributed:rounds.reduce((a,r)=>a+r.rewardPool,0)}));app.post('/api/admin/config',auth,(q,s)=>{const {tokenMint,feeWallet,intervalMinutes}=q.body;if(!tokenMint||!feeWallet)return s.status(400).json({error:'Token mint and fee wallet required'});settings={...settings,tokenMint,feeWallet,rewardBps:5000,intervalMinutes:Number(intervalMinutes)||5,status:'ready'};watermark=null;s.json(settings)});app.post('/api/admin/run-cycle',auth,async(q,s)=>{await cycle();s.json({ok:true,rounds:rounds.length})});setInterval(cycle,300000);app.listen(process.env.PORT||3000,()=>console.log('Rewards bot ready'));
